global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'podinfo-backend'
    static_configs:
      - targets: ['backend_blue:9898', 'backend_green:9898']
        labels:
          service: podinfo-backend

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
